version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - type: volume
        source: MONGO_DATA2
        target: /data/db
      - type: volume
        source: MONGO_CONFIG2
        target: /data/configdb
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - "mongodb"
    restart: unless-stopped

volumes:
  MONGO_DATA2:
    name: MONGO_DATA2
  MONGO_CONFIG2:
    name: MONGO_CONFIG2